- hosts: all
  become: yes
  serial: 1

  tasks:
    - name: Include Ansible vault
      include_vars:
        file: ../roles/vars/vault.yml
        name: vault

    - name: Copy all Dockerfile
      copy:
        src: ../roles/templates
        dest: /home/{{ ansible_user }}
        mode: preserve

    - name: Template the .env file
      template:
        src: ../roles/templates/.env.j2
        dest: /home/{{ ansible_user }}/templates/.env

    - name: Run Docker Compose
      command: docker-compose -f /home/{{ ansible_user }}/templates/docker-compose.yml up --build -d