- name: just stop all and down all containers
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: docker compose down
      ansible.builtin.command:
        cmd: "docker-compose -f /home/{{ ansible_user }}/templates/docker-compose.yml down "
      ignore_errors: yes